executable = k3pi_signal_cuts/scripts/optimise/optimise.sh
universe   = vanilla
output     = output.$(cluster).$(process).out
error      = error.$(cluster).$(process).err
log        = log.$(cluster).$(process).log

RequestCpus = 8
RequestGpus = 0

+MaxRuntime = 600

transfer_input_files = python.tar.gz

stream_output=True
stream_error=True

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT

environment = CONDOR_JOB_ID=$(cluster)

queue 1
